### ISSUE TITLE
Update switches file

### ISSUE THREAD

**Issue by senier** [Componolit/ada-style#5]
Update switches once Componolit/RecordFlux#207 is done.

**Comment by jklmnn** [comment]
I manually went through the switches before adding them. The current setup includes basically all available switches that do not loosen the strictness of the style checker. If we turn off switches in generated RFLX code I would not want to incorporate this change here. The switches here should apply to hand written code which should be handled stricter than generated code.

**Comment by senier** [comment]
I believe you took a different perspective on the switches. In the RecordFlux ticket above we also look into (non style-related) validity checks. For this repository it makes sense to only consider the style-related switches. I still think that this part should be identical between all of our projects - if the need arises to disable some style checks for generated code then we'll do this through a pragma in the code, not by using a different set of switches.

I'll keep this ticket open to track that we really come up with the same style switches in RecordFlux.

@jklmnn NB: The switches file should be named `style.gpr` to match the project name and the purpose.

**Comment by jklmnn** [comment]
Ah okay, it sounded to me as if we wanted to adapt the switches here to what we need in RecordFlux.

Yes, I already renamed the project but forgot the file, I'll fix that.

**Comment by treiher** [comment]
There is also a typo and a missing semicolon at the end of the file:

```Ada
end Swtyle
```

**Comment by jklmnn** [comment]
Thanks for the hint, I fixed it.

**Comment by senier** [comment]
The semicolon is still missing:

```sh
$  gprbuild -P style.gpr 
style.gpr:32:01: ";" expected
gprbuild: "style.gpr" processing failed
```

Now when we have the style guide in the repository, we should refrain from pushing changes to master directly, but use the proper way through a PR.

**Comment by jklmnn** [comment]
> Now when we have the style guide in the repository, we should refrain from pushing changes to master directly, but use the proper way through a PR.

I initially thought that it would be fixed with a single commit, but apparently there were more problems ;) Is it okay when I squash push that (hopefully) last fix into the last commit directly on master?

**Comment by senier** [comment]
Too late, I just enabled branch protection ;) Please create an `issue_5` branch and file a PR.

**Comment by treiher** [comment]
Is there anything left to do here?

**Comment by jklmnn** [comment]
The commits referenced here are already on master and so far I can't remember anything that still needs to be done here. I'll close this and we can reopen it if we find something that is missing.
